## service 'ManipulationCommand.srv'

## REQUEST

# home position (true: manipulator in home position; true: manipulator near the marker)
bool home_position

# the waypoint
string waypoint

---

## RESPONSE

# operation success or not
bool success
