## service 'ManipulatorPosition', proided by the manipulation controller

# REQUEST

# position identifier
int32 command

---

# RESPONSE

# does the operation succeeded?
bool success

# in case of problems
string details
