## service 'ManipulatorPosition', proided by the manipulation controller

# REQUEST

# 0 -- home
# 1 -- extended
# 2 -- low
# 3 -- front_low
# 4 -- front_high

# position identifier
int32 command

---

# RESPONSE

# does the operation succeeded?
bool success

# in case of problems
string details
