## file 'AddHint.srv'
# it represents a hint of the type -> (Aelem, Belem):property

# the numeric ID of the hint
int32 hypID

# fields of the property
string property
string Belem

---

bool success
